### ISSUE TITLE
Cluster-Wide IPAM

### ISSUE THREAD

**Issue by BurlyLuo** [cloudnativer/kube-ipam#1]
```
etcdConfig, an object of etcd address info
etcdURL (string, required): The URL of etcd
etcdCertFile (string, required): The cert file of etcd
etcdKeyFile (string, required): The key file of etcd
etcdTrustedCAFileFile (string, required): The ca file of etcd
```
do we test combine with the mutiple CNI ,like Multus?

another QA: do we have a plan to support the data-store with kubernetes?

**Comment by houseonline** [comment]
> do we test combine with the mutiple CNI ,like Multus?
> 

Yes, we made Multus cni compatible, see https://github.com/cloudnativer/kube-ipam/blob/main/docs/Networksecuritylayering.md  for details

**Comment by houseonline** [comment]
> another QA: do we have a plan to support the data-store with kubernetes?

Yes , we are planning to support the data-store with kubernetes.

We will start to support it in version 0.2.0. 

Stay tuned.

**Comment by cloudnativer** [comment]
Version v0.2.0 has been officially released. You can download the experience. 
https://github.com/cloudnativer/kube-ipam/releases/tag/v0.2.0
